services:
  gt7_tool:
    build: .
    container_name: gt7_tool_car_attitude2
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./:/app
    environment:
      - PS5_IP=192.168.1.10
      - PYTHONUNBUFFERED=1
